apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-assistant
  namespace: statex-apps
  labels:
    app: shop-assistant
    managed-by: k8s-migration
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - shop-assistant.alfares.cz
      secretName: shop-assistant-tls
  rules:
    - host: shop-assistant.alfares.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shop-assistant
                port:
                  number: 4500
