apiVersion: v1
kind: Service
metadata:
  name: shop-assistant
  namespace: statex-apps
  labels:
    app: shop-assistant
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: shop-assistant
  ports:
    - protocol: TCP
      port: 4500
      targetPort: 4500
      name: app
