#!/usr/bin/env bash
set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
VAULT_PATH="${VAULT_PATH:-secret/prod/shop-assistant-smoke}"
OUTPUT_ENV="${OUTPUT_ENV:-.env.sa-g7-smoke}"
TOKEN_DIR="${TOKEN_DIR:-/tmp/sa-g7-smoke-tokens}"
BASE_URL="${BASE_URL:-https://shop-assistant.alfares.cz}"
REQUIRE_TOKEN_SMOKE="${REQUIRE_TOKEN_SMOKE:-1}"
SA_G7_TOKEN_HELPER_DRY_RUN="${SA_G7_TOKEN_HELPER_DRY_RUN:-0}"

export VAULT_ADDR

if [ "$SA_G7_TOKEN_HELPER_DRY_RUN" != "1" ] && ! command -v vault >/dev/null 2>&1; then
  echo "Missing required command: vault" >&2
  exit 1
fi
if ! command -v node >/dev/null 2>&1; then
  echo "Missing required command: node" >&2
  exit 1
fi

mkdir -p "$TOKEN_DIR"
chmod 700 "$TOKEN_DIR"

if [ "$SA_G7_TOKEN_HELPER_DRY_RUN" = "1" ]; then
  secret_json='{"data":{"data":{"AUTH_BASE_URL":"https://auth.alfares.cz","CUSTOMER_EMAIL":"dry-run-customer@example.invalid","CUSTOMER_PASSWORD":"dry-run","ADMIN_EMAIL":"dry-run-admin@example.invalid","ADMIN_PASSWORD":"dry-run","NON_ADMIN_EMAIL":"dry-run-non-admin@example.invalid","NON_ADMIN_PASSWORD":"dry-run"}}}'
else
  secret_json="$(vault kv get -format=json "$VAULT_PATH")"
fi
SECRET_JSON="$secret_json" BASE_URL="$BASE_URL" REQUIRE_TOKEN_SMOKE="$REQUIRE_TOKEN_SMOKE" OUTPUT_ENV="$OUTPUT_ENV" TOKEN_DIR="$TOKEN_DIR" SA_G7_TOKEN_HELPER_DRY_RUN="$SA_G7_TOKEN_HELPER_DRY_RUN" node <<'NODE_TOKENS'
const fs = require("fs");
const path = require("path");
const secret = JSON.parse(process.env.SECRET_JSON).data.data || {};
const required = ["AUTH_BASE_URL", "CUSTOMER_EMAIL", "CUSTOMER_PASSWORD", "ADMIN_EMAIL", "ADMIN_PASSWORD", "NON_ADMIN_EMAIL", "NON_ADMIN_PASSWORD"];
for (const key of required) {
  if (!secret[key]) throw new Error(`Vault secret missing ${key}`);
}
const authBaseUrl = String(secret.AUTH_BASE_URL).replace(/\/$/, "");
async function login(email, password, label) {
  if (process.env.SA_G7_TOKEN_HELPER_DRY_RUN === "1") {
    return `dry-run-${label}-token`;
  }
  const response = await fetch(`${authBaseUrl}/auth/login`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ email, password })
  });
  if (![200, 201].includes(response.status)) {
    const text = await response.text();
    throw new Error(`${label} login failed: HTTP ${response.status} ${text.slice(0, 120)}`);
  }
  const body = await response.json();
  if (!body.accessToken) throw new Error(`${label} login did not return accessToken`);
  return body.accessToken;
}
function quote(value) {
  return JSON.stringify(String(value));
}
function writeTokenFile(name, value) {
  const dir = process.env.TOKEN_DIR || "/tmp/sa-g7-smoke-tokens";
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  fs.chmodSync(dir, 0o700);
  const file = path.join(dir, name);
  fs.writeFileSync(file, `${value}\n`, { mode: 0o600 });
  fs.chmodSync(file, 0o600);
  return file;
}
(async () => {
  const customerToken = await login(secret.CUSTOMER_EMAIL, secret.CUSTOMER_PASSWORD, "customer");
  const adminToken = await login(secret.ADMIN_EMAIL, secret.ADMIN_PASSWORD, "admin");
  const nonAdminToken = await login(secret.NON_ADMIN_EMAIL, secret.NON_ADMIN_PASSWORD, "non-admin");
  const customerTokenFile = writeTokenFile("customer.token", customerToken);
  const adminTokenFile = writeTokenFile("admin.token", adminToken);
  const nonAdminTokenFile = writeTokenFile("non-admin.token", nonAdminToken);
  const lines = [
    "# Generated by scripts/sa-g7-token-env-from-vault.sh. Do not commit.",
    `BASE_URL=${quote(process.env.BASE_URL || "https://shop-assistant.alfares.cz")}`,
    `REQUIRE_TOKEN_SMOKE=${quote(process.env.REQUIRE_TOKEN_SMOKE || "1")}`,
    `CUSTOMER_TOKEN_FILE=${quote(customerTokenFile)}`,
    `ADMIN_TOKEN_FILE=${quote(adminTokenFile)}`,
    `NON_ADMIN_TOKEN_FILE=${quote(nonAdminTokenFile)}`,
    ""
  ];
  fs.writeFileSync(process.env.OUTPUT_ENV || ".env.sa-g7-smoke", lines.join("\n"), { mode: 0o600 });
})().catch((error) => { console.error(error.message); process.exit(1); });
NODE_TOKENS
chmod 600 "$OUTPUT_ENV"
echo "Wrote strict smoke token-file env to ${OUTPUT_ENV}."
echo "Wrote token files under ${TOKEN_DIR}."
echo "Exported key names: BASE_URL REQUIRE_TOKEN_SMOKE CUSTOMER_TOKEN_FILE ADMIN_TOKEN_FILE NON_ADMIN_TOKEN_FILE"
if [ "$SA_G7_TOKEN_HELPER_DRY_RUN" = "1" ]; then
  echo "Dry-run mode used synthetic placeholder tokens only; Vault/Auth were not contacted."
fi
